### ISSUE TITLE
Metering Demo

### ISSUE THREAD

**Issue by Teckiee** [featherbear/presonus-studiolive-api-demo#1]
Hi,
Probably a pebkac issue. I'm trying to get the metering demo site working on an rPi. Getting the following on the console:
`{"level":"info","message":"PreSonus StudioLive API meter demo starting","timestamp":"2022-02-22T13:33:23.876Z"}
{"level":"info","message":"Creating API client instance","timestamp":"2022-02-22T13:33:23.882Z"}
{"level":"info","message":"Connecting to console on 192.168.5.132:53000","timestamp":"2022-02-22T13:33:23.884Z"}
{"level":"info","message":"Webserver listening on 0.0.0.0:8080","timestamp":"2022-02-22T13:33:24.030Z"}
Unhandled message code CK
Unhandled message code CK
`
The connection is visible on the Universal Control app, but the webpage of the demo is blank. Studiolive 16 desk.

My eventual hope was to turn the metering data from the api into a physical led array that I can mount to the top of my SL16. 16 leds per channel instead of the built in 3, while being physically located above the channels instead of the ipad app meters which are not physically relatable to the desk itself.

**Comment by featherbear** [comment]
Not a pebcak issue 😉

In https://github.com/featherbear/presonus-studiolive-api/commit/55e1593193c89cedd3b085aec1dbf646ffd8efe7 I introduced a change that required the client to wait for certain data (console state) that the console would send, before successfully being connected.

However at times the incoming data would be compressed (aka the `CK` code) - but at the moment I don't yet know how to decode it. It's currently a blocker. I understand some uses of the API might not require the console state (i.e. metering); so I might add in a setting to skip the console state until I figure out how to decode it - how does that sound?

btw your project idea sounds fantastic; something that I was also thinking of doing; similar to the M7CL meter bridge!

**Comment by Teckiee** [comment]
That would be awesome if you could. My alternative is getting the audio level data using the analog connectors. Obviously not nearly as good an option. And yeah, the M7CL looks like what I'm trying to do. I miss the input meters that the 24.4.2 had. I still have to figure out how to get the metering data into a state I can use, but I wanted to see how your demo worked first. javascript/typescript is not something I've used before.

**Comment by featherbear** [comment]
Sure, i'll add that into my backlog

For now, there's an absolute mess of Python code which I originally developed this API on
https://github.com/featherbear/presonus-studiolive-api/tree/research_python

I got it to a point where it was able to receive the UDP metering data

**Comment by featherbear** [comment]
👋 @Teckiee Metering seems to work, as I've gotten past the `CK` packet roadblock.
In terms of using the data, assuming you'll write some C/C++/Python code to interface with your LED strips - You can try repurpose the metering demo, and write your own Socket.IO / WebSocket client code logic to receive the metering data stream
